### ISSUE TITLE
Ajouter des liens ou sortir des releases pour des versions builds

### ISSUE THREAD

**Issue by yannis300307** [CoCoSol007/casino-dingo#4]
Par exemple, inclure dans le readme les liens vers [yannis300307.fr/casino-dingo/](https://yannis300307.fr/casino-dingo/)

et les autres liens de téléchargement vers les versions Windows, Android, etc...

**Comment by CoCoSol007** [comment]
closed by this [commit](https://github.com/CoCoSol007/casino-dingo/commit/32308a04c09e23037d7149d975d94ce4c5ac3542)
