### ISSUE TITLE
Il est possible de retourner au menu pendant le tirage à la machine à sous et au black Jack

### ISSUE THREAD

**Issue by yannis300307** [CoCoSol007/casino-dingo#7]
Cela est pratique en speedrun mais cela constitue quand même un bug car il permet d'avoir 0 FCC et 0 $ en même temps.
Je laisse les créateurs du jeu juger de la volonté de le fix.

**Comment by CoCoSol007** [comment]
Pour moi, c'est un bug, car nous ne sommes pas censés avoir 0 FCC et 0 $.

**Comment by yannis300307** [comment]
Dans ce cas là est ce que l'on considère les quêtes en attente de récupération comme de l'argent potentiel ?
